# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_page_pagetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(0, 3600))),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_all_day', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('has_end_date', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich'), ('yearly', 'Jährlich')], default=None, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('adress', models.CharField(max_length=250)),
                ('postcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.POI'),
        ),
    ]
