# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0003_event-poi'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'Ausstehender Review'), ('public', 'Veröffentlicht')], default='draft', max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('permalink', models.CharField(max_length=60)),
                ('language', models.CharField(max_length=2)),
                ('version', models.PositiveIntegerField(default=0)),
                ('active_version', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='POITranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'Ausstehender Review'), ('public', 'Veröffentlicht')], default='draft', max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('permalink', models.CharField(max_length=60)),
                ('language', models.CharField(max_length=2)),
                ('version', models.PositiveIntegerField(default=0)),
                ('active_version', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='poi',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='description',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='name',
        ),
        migrations.AddField(
            model_name='poitranslation',
            name='poi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_translations', to='cms.POI'),
        ),
        migrations.AddField(
            model_name='poitranslation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtranslation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_translations', to='cms.Event'),
        ),
        migrations.AddField(
            model_name='eventtranslation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
