# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_eventtranslation_poitranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='has_end_date',
            new_name='has_recurring_end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d'),
        ),
    ]
