# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0006_auto_20181211_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d')),
                ('is_all_day', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('has_recurring_end_date', models.BooleanField(default=False)),
                ('recurring_end_date', models.DateField(blank=True, default=None, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich'), ('yearly', 'Jährlich')], default=None, max_length=7, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.POI')),
            ],
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'Ausstehender Review'), ('public', 'Veröffentlicht')], default='draft', max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('permalink', models.CharField(max_length=60)),
                ('language', models.CharField(max_length=2)),
                ('version', models.PositiveIntegerField(default=0)),
                ('active_version', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_translations', to='cms.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
